version: '3.8'

services:

  # API de E-commerce
  ecommerce-api:
    build:
      context: .
      dockerfile: Ecommerce.API/Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    depends_on:
      - ecommerce-db
      - rabbitmq
    env_file:
      - .env
    environment:
      - DB_HOST=ecommerce-db
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASS=${DB_PASS}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Stripe__SecretKey=${STRIPE_SECRETKEY}
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__DefaultConnection=Server=ecommerce-db,1433;Database=EcommerceDB;User ID=sa;Password=${DB_PASS};TrustServerCertificate=True
    volumes:
      - "${USERPROFILE}/.aspnet/https:/https:ro"
      - ./certs:/https:ro

  # SQL Server
  ecommerce-db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASS}

  # RabbitMQ
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
 
volumes:
   sonardata: {}
   sonarqube_data: {}
   sonarqube_extensions: {}
   sonarqube_logs: {}
