name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

env:
  DOTNET_VERSION: '8.0.x'
  SLN_FILE: 'Ecommerce.sln'

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Create .env file
        run: |
          cat > .env << EOF
          DB_PASS=Your_password123!
          JWT_KEY=${{ secrets.JWT_KEY }}
          JWT_ISSUER=${{ secrets.JWT_ISSUER }}
          JWT_AUDIENCE=${{ secrets.JWT_AUDIENCE }}
          STRIPE_SECRETKEY=${{ secrets.STRIPE_SECRETKEY }}
          STRIPE_PUBLISHABLEKEY=${{ secrets.STRIPE_PUBLISHABLEKEY }}
          API_URL=${{ secrets.API_URL }}
          API_TOKEN=${{ secrets.API_TOKEN }}
          DEFAULT_ORIGIN_ZIPCODE=01001000
          SERVICES=1,2,18
          USE_MOCK_DATA=false
          DEFAULT_PACKAGE_WIDTH=10
          DEFAULT_PACKAGE_HEIGHT=10
          DEFAULT_PACKAGE_LENGTH=10
          DEFAULT_PACKAGE_WEIGHT=1
          DEFAULT_INSURANCE_VALUE=0
          DB_HOST=ecommerce-db
          DB_NAME=EcommerceDB
          DB_USER=sa
          DB_PORT=1433
          EOF

      - name: Start services with Docker Compose
        run: docker compose up --build -d

      - name: Build and Test
        run: |
          dotnet build ${{ env.SLN_FILE }} --configuration Release --no-incremental

          dotnet test ${{ env.SLN_FILE }} \
            --no-build \
            --configuration Release \
            --logger "trx;LogFileName=test_results.trx" \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            /p:CoverletOutput=TestResults/Coverage/

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            **/TestResults/**/*.trx
            **/TestResults/**/coverage.opencover.xml

      - name: Cleanup
        if: always()
        run: docker compose down

  sonarqube-analysis:
    needs: build-test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install SonarScanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Create .env file
        run: |
          cat > .env << EOF
          DB_PASS=Your_password123!
          JWT_KEY=${{ secrets.JWT_KEY }}
          JWT_ISSUER=${{ secrets.JWT_ISSUER }}
          JWT_AUDIENCE=${{ secrets.JWT_AUDIENCE }}
          STRIPE_SECRETKEY=${{ secrets.STRIPE_SECRETKEY }}
          STRIPE_PUBLISHABLEKEY=${{ secrets.STRIPE_PUBLISHABLEKEY }}
          API_URL=${{ secrets.API_URL }}
          API_TOKEN=${{ secrets.API_TOKEN }}
          DEFAULT_ORIGIN_ZIPCODE=01001000
          SERVICES=1,2,18
          USE_MOCK_DATA=false
          DEFAULT_PACKAGE_WIDTH=10
          DEFAULT_PACKAGE_HEIGHT=10
          DEFAULT_PACKAGE_LENGTH=10
          DEFAULT_PACKAGE_WEIGHT=1
          DEFAULT_INSURANCE_VALUE=0
          DB_HOST=ecommerce-db
          DB_NAME=EcommerceDB
          DB_USER=sa
          DB_PORT=1433
          EOF

      - name: Start SonarQube
        run: docker compose up -d sonarqube-db sonarqube

      - name: Wait for SonarQube
        run: |
          echo "Waiting for SonarQube to be ready..."
          timeout 300 bash -c 'until curl -s http://localhost:9000/api/system/status | grep -q "UP"; do sleep 5; done'
          echo "SonarQube is ready!"

      - name: SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin \
            /k:"ecommerce" \
            /n:"Ecommerce" \
            /d:sonar.host.url="http://localhost:9000" \
            /d:sonar.login="${{ env.SONAR_TOKEN }}" \
            /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" \
            /d:sonar.cs.vstest.reportsPaths="**/TestResults/**/*.trx" \
            /d:sonar.coverage.exclusions="**/Migrations/**,**/Resources/**/DTOs/**,**/Resources/**/Requests/**,**/Resources/**/Responses/**,**/Program*.cs" \
            /d:sonar.sourceEncoding="UTF-8"

          dotnet build ${{ env.SLN_FILE }} --configuration Release --no-incremental

          dotnet test ${{ env.SLN_FILE }} \
            --no-build \
            --configuration Release \
            --logger "trx;LogFileName=test_results.trx" \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            /p:CoverletOutput=TestResults/Coverage/

          dotnet sonarscanner end /d:sonar.login="${{ env.SONAR_TOKEN }}"

      - name: Cleanup SonarQube
        if: always()
        run: docker compose down

  docker-build:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Ecommerce.API/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/ecommerce-api:latest
            ghcr.io/${{ github.repository }}/ecommerce-api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
