name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  DOTNET_VERSION: '8.0.x'
  SLN_FILE: 'Ecommerce.sln'
  DOCKER_IMAGE_NAME: ecommerce-api
  DOCKER_REGISTRY: ghcr.io

jobs:
  build-test-sonar-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install SonarScanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Create .env file with all secrets
        run: |
          cat > .env << EOF
          DB_PASS=Your_password123!
          DB_HOST=ecommerce-db
          DB_NAME=EcommerceDB
          DB_USER=sa
          DB_PORT=1433
          JWT_KEY=${{ secrets.JWT_KEY }}
          JWT_ISSUER=${{ secrets.JWT_ISSUER }}
          JWT_AUDIENCE=${{ secrets.JWT_AUDIENCE }}
          STRIPE_SECRETKEY=${{ secrets.STRIPE_SECRETKEY }}
          STRIPE_PUBLISHABLEKEY=${{ secrets.STRIPE_PUBLISHABLEKEY }}
          API_URL=${{ secrets.API_URL }}
          API_TOKEN=${{ secrets.API_TOKEN }}
          SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}
          DEFAULT_ORIGIN_ZIPCODE=01001000
          SERVICES=1,2,18
          USE_MOCK_DATA=false
          DEFAULT_PACKAGE_WIDTH=10
          DEFAULT_PACKAGE_HEIGHT=10
          DEFAULT_PACKAGE_LENGTH=10
          DEFAULT_PACKAGE_WEIGHT=1
          DEFAULT_INSURANCE_VALUE=0
          EOF

      - name: Start all services (SQL, RabbitMQ, SonarQube)
        run: docker compose up --build -d

      - name: Wait for SQL Server
        run: |
          echo "Waiting for SQL Server..."
          timeout 60 bash -c 'until nc -z $DB_HOST $DB_PORT; do sleep 2; done'

      - name: Wait for RabbitMQ
        run: |
          echo "Waiting for RabbitMQ..."
          TIMEOUT=60
          ELAPSED=0
          while ! docker exec -it $(docker ps -qf "name=rabbitmq") rabbitmqctl status >/dev/null 2>&1; do
            sleep 2
            ELAPSED=$((ELAPSED+2))
            if [ $ELAPSED -ge $TIMEOUT ]; then
              echo "Timeout waiting for RabbitMQ"
              exit 1
            fi
          done
          echo "RabbitMQ is ready!"

      - name: Wait for SonarQube
        run: |
          echo "Waiting for SonarQube..."
          timeout 300 bash -c 'until curl -s http://localhost:9000/api/system/status | grep -q "UP"; do sleep 5; done'

      - name: Build API
        run: dotnet build ${{ env.SLN_FILE }} --configuration Release --no-incremental

      - name: Run Tests and Collect Coverage
        run: |
          dotnet test ${{ env.SLN_FILE }} \
            --no-build \
            --configuration Release \
            --logger "trx;LogFileName=test_results.trx" \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            /p:CoverletOutput=TestResults/Coverage/

      - name: SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin \
            /k:"ecommerce" \
            /n:"Ecommerce" \
            /d:sonar.host.url="http://localhost:9000" \
            /d:sonar.login="$SONAR_TOKEN" \
            /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" \
            /d:sonar.cs.vstest.reportsPaths="**/TestResults/**/*.trx" \
            /d:sonar.coverage.exclusions="**/Migrations/**,**/Resources/**/DTOs/**,**/Resources/**/Requests/**,**/Resources/**/Responses/**,**/Program*.cs" \
            /d:sonar.sourceEncoding="UTF-8"

          dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            **/TestResults/**/*.trx
            **/TestResults/**/coverage.opencover.xml

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Ecommerce.API/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/ecommerce-api:latest
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/ecommerce-api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Cleanup
        if: always()
        run: docker compose down -v
